### ISSUE TITLE
Another templating system

### ISSUE THREAD

**Issue by arnostpleskot** [SYMBIO/static-devstack#4]
@pavelsuraba, @cenda, @vonschau  what do you think about using another template language with twig-like syntax?

For ex. [Nunjucks](https://mozilla.github.io/nunjucks/)?

**Comment by vonschau** [comment]
Ani vam nevim, ma to smysl? Jade ma vyhodu, kterou chapu - hezci orientace v kodu. Ale tady by se tahle vyhoda ztratila. Ma to teda vyhodu v tom, ze si backendak muze prevzit primo kusy sablony a budou mu fungovat, ale stejne to bude muset trochu prepsat, takze osobne mi to takova vyhoda neprijde. Dalsi vyhody nevim, nekoumal jsem do hloubky. Mozna je to rychlejsi, vykonnejsi, pise se v tom rychlejc, kdo vi...

**Comment by vonschau** [comment]
Kazdopadne palec nahoru za hledani nejvhodnejsiho reseni!

**Comment by arnostpleskot** [comment]
No, podle vseho by syntaxe mela bejt kompatibilni, az na pokrocilejsi filtry, ktery nejsou by default v Nunjucks a testy,jejichz implementace je jako [open enchancement](https://github.com/mozilla/nunjucks/issues/532). Ale to si myslim, ze jsou veci, ktery pokud pripravujeme sablony pro php, uplne nepotrebujeme.
A to, ze se tam nepouziva signficant whitespace nevidim uplne jako nevyhodu :), ale to je o osobnich preferencich.

Ale pokud by sme jeli tvrde BEM i s se sablonama (co blok to sablona), tak by se mel clovek v realu dostat jen na par radku v jednom souboru a tam toho moc k orientaci neni...

**Comment by vonschau** [comment]
Takze posunula se v tomhle situace? Co na to ostatni frontendaci?

**Comment by pavelsuraba** [comment]
V pondeli to ještě proberu s Arnoštem :-)

2016-02-04 10:40 GMT+01:00 Martin Cajthaml notifications@github.com:

**Comment by arnostpleskot** [comment]
No, dneska asi ne - mam dovolenou a zejtra sem v Pardubkach :)
